// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnzzuuxqlpswvemrvbzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuenp1dXhxbHBzd3ZlbXJ2YnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODc3OTIsImV4cCI6MjA1OTU2Mzc5Mn0._a125I3ZetVn-JRmeS-_qFc8yIQAEEO6R6Tb0KT9HRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);